---
title: "CTDC_data"
author: "Lindsey Greenhill"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(janitor)
library(readxl)
library(tidyverse)
```

```{r data, include=FALSE}

# reading in data from the Counter Trafficking Data Collective with 62 different
# variables. Data set made in 2017. Includes 47,000 different victims of 43
# different nationalities, with exploitation taking place across 52 different
# countries. Original data class included 80,000 observations, but after
# k-anonymization widdled down. Data set compiled through analysis of different
# data models from different contributors. Polaris and IOM cofounders of this
# project. Data set not random, not necessarily representative sample of all
# human trafficking victims. Data from Liberty Asia also included. Years frange
# from 2002 to 2017. want to keep yearOfRegistration, datasource,
# gender,majorityStatus, majorityStatusAtExploit (-99 is NA), citizenship (need
# to link with values based on iso country codes), all variables starting with
# "is", include all "typeOfLabour" variables. Might not do all of these
# initially.

ctdc_data <- read_csv("raw-data/the_global_dataset_3_sept_2018.csv", na = c("", "-99", "NA")) %>% 
  clean_names() %>%
  select(year_of_registration, datasource, gender,
         majority_status, citizenship, country_of_exploitation,
         ) %>%
    filter(year_of_registration >= 2010, citizenship != "US")
```

```{r country_code_data, include=FALSE}

# data from iso on country codes, which are used in teh ctdc data set

code_data <- read_csv("raw-data/data_csv.csv")  %>% clean_names()
code_data
```

```{r polity_data, include=FALSE}

#reading in polity data. filtering for rows where year is >= 2010, because I'm
#only using data from then. Code book for this data set important to use.
#Country codes three characters instead of two, so I will try to join based on
#the country name instead. If that doesn't work I'll find a set that converts
#from iso to alpha codes. Want to keep: country, year, polity, durable, persist

polity_data <- read_excel("raw-data/polity.xls") %>%
  clean_names() %>%
  filter(year >= 2010) %>%
  select(country, year, polity, durable)
polity_data

```

```{r join_data, include=FALSE}

# joined by iso country codes. Had to use inner_joins because it wasn't working
# in just one. I also tried to use the suffix argument, but that  wouldn't work
# because I would have needed to inner join by the two variables at the same
# time, so I used mutate instead.

joined_country_code_data <- ctdc_data %>%
  inner_join(code_data, by = c("citizenship" = "code")) %>%
  inner_join(code_data, by = c("country_of_exploitation" = "code"))  %>%
  rename(origin_country = name.x, destination_country = name.y) %>%
  select(-majority_status, - citizenship, -country_of_exploitation, -datasource)
joined_country_code_data
```

```{r join_polity_data, include=FALSE}

# joining based on year and country name. Had the same problem joining by two
# variables as above so I had to use two inner joins. renamed the columns also
# because suffix argument not working.

joined_ctdc_code_polity <- joined_country_code_data %>%
    inner_join(polity_data, by = c("year_of_registration" = "year",
                                   "origin_country" = "country")) %>%
  inner_join(polity_data, by = c("year_of_registration" = "year", 
                                 "destination_country" = "country")) %>%
  rename(polity_origin = polity.x, durable_origin = durable.x, 
         polity_destination = polity.y, 
         durable_destination = durable.y,
         year = year_of_registration)

```

```{r playing, include=FALSE}

#playing around with data to see prevalences

joined_country_code_data %>% count(origin_country, sort = TRUE)
joined_country_code_data %>% count(destination_country, sort = TRUE)
joined_country_code_data %>% group_by(origin_country,
                                      destination_country) %>% 
  summarize(n())

# data set without the transition countries 
x <- joined_ctdc_code_polity %>% filter(polity_origin > -12,
                                        polity_destination > -12)
# histograms of polity origin and polity destination
ggplot(x, aes(polity_origin)) +
  geom_histogram()
ggplot(x, aes(polity_destination)) +
  geom_histogram()

# adding a difference column of polity origin and destination
diff<- joined_ctdc_code_polity %>% filter(origin_country != destination_country,
                                          polity_origin > -13, 
                                          origin_country != "United States") %>%
  mutate(difference = polity_origin - polity_destination)
# summary of the average of the differences, = 1 ish 
sum <- diff %>% summarize(avg = mean(difference))
sum
# distribution of differences 
ggplot(diff, aes(difference)) +
  geom_histogram()


```

```{r playing2, include=FALSE}

# looking at relationship between polity of origin and destination, doesn't seem
# to be a relationship

ggplot(diff, aes(x = polity_origin, y = polity_destination)) +
  geom_point()
```
```{r playing3, echo=FALSE}

# bar charts of origin countries

by_origin <- ggplot(joined_country_code_data,
                    aes(origin_country)) +
  geom_bar() +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90))
by_origin

# list with top five origin countries
top_five_origin <- joined_country_code_data %>%
  count(origin_country, sort=TRUE) %>%
  slice(1:5) %>% pull(origin_country)
```



```{r Cambodia, echo=FALSE}

# data set with just Cambodia information. Plot showing destination countries

Cambodia <- joined_ctdc_code_polity %>%
  filter(origin_country == "Cambodia") 
Cambodia_destinations <- ggplot(Cambodia, aes(destination_country)) +
  geom_bar() +
  labs(title = "Cambodia's Destination Countries")
Cambodia_destinations

```

```{r Philipinnes, echo=FALSE}

# data set identical to Cambodia but with Philippines. Plot showing destination
# countries

Philippines <- joined_ctdc_code_polity %>%
  filter(origin_country == "Philippines") 
Philippines_destinations <- ggplot(Philippines, aes(destination_country)) +
  geom_bar() +
  labs(title = "Philippines's Destination Countries")
Philippines_destinations
```

```{r allCountries, echo=FALSE}

# I created a new data set by binding the rows of two new data sets that just
# contain the origin and destination countries. I renamed the columns in the
# select statements so that the new data set I created when I binded rows only
# had a country column and an id column. I then used the case_when function to
# rename those ids. I had to change the angle of the names for the ggplot so I
# could read all of the country names.

origins <- joined_ctdc_code_polity %>% select(country = origin_country)
destinations <- joined_ctdc_code_polity %>% select(country = destination_country)

bind <- bind_rows(origins, destinations, .id = "id") %>%
  mutate(id = case_when(id == 1 ~ "origin country", 
                        id == 2 ~ "destination country"))
ggplot(bind, aes(country, fill = id)) +
  geom_bar(position = "dodge") +
  labs(title = "Counts of Countries by Origin and Destination") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

```









