---
title: "final_project_organized_1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(janitor)
library(readxl)
library(ggthemes)
library(ggsci)
library(gt)
library(readxl)
library(rnaturalearth)
library(rnaturalearthdata)
library(xml2)
library(rvest)
library(sf)
library(broom)
library(rgeos)
library(ggrepel)
library(tidyverse)
```

```{r data, include=FALSE}

# reading in data from the Counter Trafficking Data Collective with 62 different
# variables. Data set made in 2017. Includes 47,000 different victims of 43
# different nationalities, with exploitation taking place across 52 different
# countries. Original data class included 80,000 observations, but after
# k-anonymization widdled down. Data set compiled through analysis of different
# data models from different contributors. Polaris and IOM cofounders of this
# project. Data set not random, not necessarily representative sample of all
# human trafficking victims. Data from Liberty Asia also included. Years frange
# from 2002 to 2017. want to keep yearOfRegistration, datasource,
# gender,majorityStatus, majorityStatusAtExploit (-99 is NA), citizenship (need
# to link with values based on iso country codes), all variables starting with
# "is", include all "typeOfLabour" variables. Might not do all of these
# initially.

ctdc_data <- read_csv("raw-data/the_global_dataset_3_sept_2018.csv", na = c("", "-99", "NA")) %>% 
  clean_names() %>%
  select(year_of_registration, datasource, gender,
         majority_status,
         citizenship, type_of_exploit_concatenated,
         country_of_exploitation,
         ) %>%
  mutate(type = case_when(
          type_of_exploit_concatenated == "Forced labour" ~ "Forced Labor",
          type_of_exploit_concatenated == "Forced marriage" ~ "Forced Marriage",
          type_of_exploit_concatenated == "Sexual exploitation" ~ "Sexual Exploitation",
          type_of_exploit_concatenated == "Slavery and similar practices"  ~ "Slavery",
          TRUE ~ "Other")) %>%
  rename(age = majority_status) %>%
    filter(year_of_registration >= 2010)
  
```

```{r country_code_data, include=FALSE}

# data from iso on country codes, which are used in the ctdc data set joined to ctdc data 

code_data <- read_csv("raw-data/data_csv.csv")  %>% clean_names()

joined_data <- ctdc_data %>%
  left_join(code_data, by = c("citizenship" = "code")) %>%
  inner_join(code_data, by = c("country_of_exploitation" = "code"))  %>%
  rename(origin_country = name.x, destination_country = name.y) %>%
  select(-citizenship, -country_of_exploitation, -datasource)
```

```{r GSI_data, include=FALSE}

scrape_url <- "https://www.globalslaveryindex.org/2018/methodology/vulnerability/#table:13"
GSI <- read_html(scrape_url) %>%
  html_nodes(xpath = "/html/body/main/section/div/div/article/section[8]/div/div[2]/table") %>%
  html_table() %>%
  data.frame() %>%
  clean_names() %>%
  select(country, overall_weighted_average)

combinations_GSI <- joined_data %>%
  count(origin_country, destination_country, sort = T) %>%
  mutate(origin_country = case_when(origin_country == "Russian Federation" ~ "Russia",
                                    origin_country == "Viet Nam" ~ "Vietnam",
                                    origin_country == "Taiwan, Province of China" ~ "Taiwan, China",
                                    origin_country == "Hong Kong" ~ "Hong Kong, China",
                                    origin_country == "Korea, Republic of" ~ "Korea, Democratic People’s Republic of (North Korea)",
                                    TRUE ~ origin_country),
         destination_country = case_when(destination_country == "Russian Federation" ~ "Russia",
                                    destination_country == "Viet Nam" ~ "Vietnam",
                                    destination_country == "Taiwan, Province of China" ~ "Taiwan, China",
                                    destination_country == "Hong Kong" ~ "Hong Kong, China",
                                    destination_country == "Korea, Republic of" ~ "Korea, Democratic People’s Republic of (North Korea)",
                                    TRUE ~ destination_country))

GSI_joined <- full_join(combinations_GSI, GSI, by = c("origin_country" = "country")) %>%
  rename(origin_score = overall_weighted_average) %>%
  left_join(GSI, by = c("destination_country" = "country")) %>%
  rename(destination_score = overall_weighted_average) %>%
  filter(n > 0, origin_country != is.na(origin_country)) %>%
  mutate(difference = destination_score - origin_score)
```

```{r GSI_regression, echo=FALSE}

lm(destination_score ~ origin_score, data = GSI_joined)

```


```{r GSI_graph, echo=FALSE}

gsi_graph1 <- ggplot(GSI_joined, aes(origin_score, destination_score)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(title = "GSI Vulnerability Scores",
       subtitle = "Positive Relationship between\n origin country score
       and destination country score",
       x = "Origin Country Score",
       y = "Destination Country Score") +
  theme_classic()

# this graph is including when people move countries and don't and excluding
# United States. this means that on average individuals are going from more
# vulnerable countries to less vulnerable countries

G_2 <- GSI_joined %>% filter(destination_country != "United States",
                             difference != is.na(difference)) %>%
  summarize(mean_diff = mean(difference)) %>% pull() %>%
  round(2)

gsi_graph2 <- GSI_joined %>% filter(destination_country != "United States") %>%
  ggplot(aes(difference)) +
  geom_histogram(binwidth = 4) +
  geom_vline(xintercept = G_2, color = "blue") +
  labs(title = "Distribution of Differences of Destination\n
       and Origin GSI Vulnerability Scores",
       subtitle = "Mean of -9.47",
       caption = "Data from Walkfree Foundation") +
  annotate("text", x = -17.47, y = 12, label = "Mean = -9.47", color = "blue") +
  theme_classic()

testdata <- vector()
for(i in 1:length(unique(joined_data$origin_country))){
  sub <- joined_data[joined_data$origin_country == unique(joined_data$origin_country)[i], ]
  addition <- c(unique(joined_data$origin_country)[i],
                sum(sub$type == 'Sexual Exploitation', na.rm = T),
                sum(sub$type == 'Forced Labor', na.rm = T))
  testdata <- rbind(testdata, addition)
}

testdata <- as.data.frame(testdata)
testdata[, -1] <- apply(testdata[, -1], 2, as.numeric)
colnames(testdata) <- c('origin', 'se', 'fl')
```

```{r gdp_data, echo=FALSE}
GDP <- read_excel("raw-data/WEO_Data.xls") %>%
  clean_names() %>%
  select(country, x2019)
GDP_GSI <- left_join(GSI, GDP, by = c("country")) %>%
  filter(country %in% GSI_joined$origin_country |
           country %in% GSI_joined$destination_country,
         !is.na(x2019),
         !is.na(overall_weighted_average))
  
GDP_GSI_graph <- ggplot(GDP_GSI, aes(x2019, overall_weighted_average)) +
  geom_point() +
  scale_x_log10() +
  geom_smooth(method = "lm") +
  labs(title = "Vulnerability Score vs GDP",
       subtitle = "Data points either origin or destination countries",
       x = "GDP (billions)",
       y = "Vulnerability Score",
       caption = "Data from Walkfree Foundation and IMF") +
  theme_classic()

GDP_GSI_model <- lm(overall_weighted_average ~ x2019, data = GDP_GSI) %>%
  tidy(conf.int=T) %>%
  select(term, estimate, conf.low, conf.high)

```


```{r map_prep, echo=FALSE}

world <- ne_countries(scale = "medium", returnclass = "sf")

o <- ctdc_data %>% count(citizenship) %>%
  rename("o_count" = n)

d <- ctdc_data %>% count(country_of_exploitation, sort=T) %>%
  rename("d_count" = n)
d

world_1 <- world %>% left_join(o, by = c("postal" = "citizenship"))
world_2 <- world_1 %>% left_join(d, by = c("postal" = "country_of_exploitation"))

```

```{r maps, echo=FALSE}


origins_map <- ggplot(data = world_2) +
  geom_sf(aes(fill = o_count)) +
  scale_fill_viridis_c(option = "plasma") +
  labs(title = "Map of Origin Countries",
       fill = "Count") +
  theme_classic() 
ggsave("Shiny_app/orgins_map.png")
  
destinations_map <- ggplot(data = world_2) +
  geom_sf(aes(fill = d_count)) +
  scale_fill_viridis_c(option = "plasma", trans = "sqrt") +
  labs(title = "Map of Exploitation Countries",
       fill = "Count") +
  theme_classic() 
ggsave("Shiny_app/destinations_map.png")

```


```{r o/d table, echo=FALSE}

origins <- joined_data %>%
  count(origin_country, sort = T) %>%
  slice(1:10) %>%
  gt() %>%
  tab_header(title = "Counts of Origin Countries",
             subtitle = "Top 10 displayed") %>%
  cols_label(origin_country = "Country", n = "")
ggsave("Shiny_app/origin_table.png")

destinations <- joined_data %>%
  count(destination_country, sort = T) %>%
  slice(1:10) %>%
  gt() %>%
  tab_header(title = "Counts of Destination Countries",
             subtitle = "Top 10 displayed") %>%
  cols_label(destination_country = "Country", n = "")  
ggsave("Shiny_app/destination_table.png")


combinations <- joined_data %>%
  count(origin_country, destination_country, sort = T) %>%
  slice(1:10) %>%
   gt() %>%
  tab_header(title = "Counts of Origin/Destination Pairs",
             subtitle = "Top 10 displayed") %>%
  cols_label(origin_country = "Origin", destination_country = "Destination",
             n = "")  
ggsave("Shiny_app/combination_table.png")

```


```{r exploreData, echo=FALSE}
ctdc_data %>% count(age)
ctdc_data %>% count(citizenship)
ctdc_data %>% count(country_of_exploitation)
ctdc_data %>% count(type_of_exploit_concatenated)
ctdc_data %>% count(gender)
```

```{r bygender, echo=FALSE}
gender <- ctdc_data %>%
  ggplot(aes(x = gender)) +
  geom_bar(fill = "lightblue") +
  labs(title = "Counts of Gender",
       subtitle = "Majority female",
       x = "Gender",
       y = "Count") +
  theme_classic()
ggsave("Shiny_app/gender.png")

```

```{r byage, echo=FALSE}
age <- ctdc_data %>%
  ggplot(aes(x = age)) +
  geom_bar(fill = "lightblue") +
  labs(title = "Counts of Age",
       subtitle = "Majority Adult",
       x = "Age Status",
       y = "Count") +
  theme_classic()
ggsave("Shiny_app/age.png")

```



```{r byexploit1, echo=FALSE}

# mutating the type of exploitation concatenated to reflect the most frequent
# types to make plotting easier. Note that "other" was already the most frequent
# value in the data

byexploit1 <- ctdc_data %>%
  mutate(type = case_when(
type_of_exploit_concatenated == "Forced labour" ~ "Forced Labor",
type_of_exploit_concatenated == "Forced marriage" ~ "Forced Marriage",
type_of_exploit_concatenated == "Sexual exploitation" ~ "Sexual Exploitation",
type_of_exploit_concatenated == "Slavery and similar practices"  ~ "Slavery",
TRUE ~ "Other"))

# reordering the factor levels to be reflective of their frequencies

byexploit1$type <- reorder(byexploit1$type, byexploit1$type, FUN = length)

# graph of frequencies of types 

byexploit1_graph <- byexploit1 %>%
  ggplot(aes(x = type)) +
  geom_bar(fill = "lightblue") +
  labs(title = "Counts of Different Types of Exploitation",
       subtitle  = "Other is most frequent followed by Sexual Exploitation and Forced Labor",
       x = "Type of Exploitation",
       y = "Count") +
  theme_classic()
ggsave("Shiny_app/exploitation.png")
byexploit1_graph

```


```{r all_ages, echo=FALSE}

# created stacked bar chart of all age statuses by type of exploitation

ages_by_type_stack <- byexploit1 %>%
  mutate(age = reorder(age, age, FUN = length))  %>%
  ggplot(aes(x = age, fill = type)) +
  geom_bar() +
  labs(title = "Ages by Type of Exploitation",
       x = "Age Status",
       y = "Count") +
  theme_classic() +
  scale_fill_npg()

ggsave("Shiny_app/ages_by_type.png")



```

```{r by_type_age, echo=FALSE}

# going to create a function that gives information for a certain type of
# exploitation

type_age <- function(x){
  byexploit1 %>%
    filter(type == x) %>%
    mutate(age  = reorder(age, age, FUN = length)) %>%
    ggplot(aes(x = age)) +
    geom_bar() +
    labs(title = paste("Ages of Exploitation: ", x),
         x = "Age",
         y = "Count") +
    theme_classic()
}

# using function for forced labor and sexual exploitation

labor_age <- type_age("Forced Labor")
labor_age

sex_age <- type_age("Sexual Exploitation")
```

```{r all_genders, echo=FALSE}
genders_by_type_stack <- byexploit1 %>%
  mutate(gender = reorder(gender, gender, FUN = length))  %>%
  ggplot(aes(x = gender, fill = type)) +
  geom_bar() +
  labs(title = "Gender by Type of Exploitation",
       x = "Gender Status",
       y = "Count") +
  theme_classic() +
  scale_fill_npg()

ggsave("shiny_app/gender_by_type.png")

```


```{r by_type_gender, echo=FALSE}
# going to create a function that gives information for a certain type of
# exploitation

type_gender <- function(x){
  byexploit1 %>%
    filter(type == x) %>%
    mutate(gender = reorder(gender, gender, FUN = length)) %>%
    ggplot(aes(x = gender)) +
    geom_bar() +
    labs(title = paste("Gender of Exploitation: ", x),
         x = "Gender",
         y = "Count") +
    theme_classic()
}

# using function for forced labor and sexual exploitation

labor_gender <- type_gender("Forced Labor")
labor_gender1 <- labor_gender + labs(subtitle = "Slight majority male")
labor_gender1
sex_gender <- type_gender("Sexual Exploitation")
sex_gender1 <- sex_gender + labs(subtitle = "Large majority female")
sex_gender1
```

```{r by type_demographic, echo=FALSE}
type_demographic <- function(x, demographic){
    byexploit1 %>%
    filter(type == x)  %>%
    ggplot(aes_string(x = demographic)) +
    geom_bar() +
    labs(title = paste(toupper(demographic), "of Individuals in", x)) +
    theme_classic()
}
type_demographic("Forced Labor", "age")
type_demographic("Sexual Exploitation", "age")

```

```{r US, echo=FALSE}

# we can see that the majority of exploitation in US in this data set is sexual exploitation 

USA <- byexploit1 %>%
  filter(citizenship == "US")
  
USA_type <- USA %>%
  ggplot(aes(x = type)) +
  geom_bar() +
  labs(title = "Types of Exploitation in the United States",
       subtitle = "Large majority is Sexual Exploitation",
       x = "Type of Exploitation",
       y = "Count") +
  theme_classic()
USA_type

# bar chart of age distribution in the US

USA_age <- USA %>%
  ggplot(aes(x = age)) +
  geom_bar() +
  labs(title = "Age Status in the United States",
       subtitle = "Majority are adult, but there are a significant amount of minors",
       x = "Age Status",
       y = "Count") +
  theme_classic()
USA_age
```

```{r origins}

```





